### ISSUE TITLE
Create API for province, ward, congressional unit api

### ISSUE THREAD

**Issue by VietThan** [VietThan/QuocHoiXV#5]
seem easy enough

https://victorscholz.medium.com/hosting-a-json-api-on-github-pages-47b402f72603

**Comment by nguyenkhoa2407** [comment]
okay looks good. I suppose we just need to start putting the data together and create the json

**Comment by nguyenkhoa2407** [comment]
also can you add me as collab

**Comment by VietThan** [comment]
so i was thinking it could be like this

/data/api/vietnam/province.js    - pulls the provinces and their province_id
/data/api/vietnam/districts/{province_id}   - pulls the districts in the provinces, their ids, their congress_id, and future information about the district
/data/api/vietnam/congress/{congress_id} - pulls unit name, unit's district (id or string?), candidates_id
/data/api/vietnam/candidates/{candidates_id} - pulls information about candidates

what da ya think @nguyenkhoa2407 ?

**Comment by VietThan** [comment]
so we can have our scripts to generate these in /data

**Comment by nguyenkhoa2407** [comment]
> so i was thinking it could be like this
> 
> /data/api/vietnam/province.js    - pulls the provinces and their province_id
> /data/api/vietnam/districts/{province_id}   - pulls the districts in the provinces, their ids, their congress_id, and future information about the district
> /data/api/vietnam/congress/{congress_id} - pulls unit name, unit's district (id or string?), candidates_id
> /data/api/vietnam/candidates/{candidates_id} - pulls information about candidates
> 
> what da ya think @nguyenkhoa2407 ?

Sounds good 😎

**Comment by VietThan** [comment]
Further progress will be made with [VietnamAPI](https://github.com/VietThan/VietnamAPI)
